version: '2.1'

services:
  main:
    build: .
    privileged: true # NECESSÁRIO para acessar o hardware da câmera
    devices:
      - "/dev/video0:/dev/video0" # Mapeia a câmera para dentro do contêiner